global:
  scrape_interval: "10s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "mysql_exporter"
    static_configs:
      - targets: ["mysql_exporter:9104"]
  - job_name: "backend_webapp"
    static_configs:
      - targets: ["backend_webapp:5000"]
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis_exporter:9121"]
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["nginx_exporter:9113"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]