name: "CD Pipeline"

on:
  workflow_run:
    workflows:
      - "CI Pipeline"
    types:
      - completed

jobs:
  CD_JOB:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v2
      
      - name: Deploy to Production
        run: |
          echo "Deploying to production server..."
          sleep 3
      
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          if docker build -t backend_webapp:latest .; then
            echo "::notice::Docker image built successfully."
          else
            echo "::error::Docker build failed."
            exit 1
          fi

      - name: Tag Docker Image
        run: |
          if docker tag backend_webapp:latest ${{ secrets.DOCKER_USERNAME }}/backend_webapp:latest; then
            echo "::notice::Docker image tagged successfully."
          else
            echo "::error::Docker tag failed."
            exit 1
          fi

      - name: Push Docker Image
        run: |
          if docker push ${{ secrets.DOCKER_USERNAME }}/backend_webapp:latest; then
            echo "::notice::Docker image pushed successfully."
          else
            echo "::error::Docker push failed."
            exit 1
          fi