name : "CD Pipeline"

on :
  workflow_run:
    workflows:
      - "CI Pipeline"
    types:
      - completed

jobs:
   CD_JOB:
    if : ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    steps:
      - name : Checkout Repo 
        uses: actions/checkout@v2
      
      - name : Deploy to Production
        run : |
          echo "Deploying to production server..."
          sleep 3
      
      - name: Docker Login
        uses : docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push Docker Image
        run : |
          docker build -t WebPy:latest .
          docker tag my-flask-app:latest ${{secrets.DOCKER_USERNAME}}/WebPy:latest
          docker push ${{secrets.DOCKER_USERNAME}}/WebPy:latest
          echo "Docker image pushed successfully!"