name : CI Pipeline

on : 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    

jobs :
  CI_Job:
    runs-on: ubuntu-latest
    
    steps:
      - name : Checkout Repository
        uses: actions/checkout@v2
      
      - name : Set Docker Compose
        run : |
          docker compose -f docker-compose.yml up -d --build
      
      - name : Wait for Services
        run : sleep 35
      
      - name : Test Flask App
        run : |
          docker compose exec backend_webapp pytest app/test_app.py

      - name : Logs if Failure
        if: failure()
        run: |
          docker compose logs backend_webapp
          docker compose logs db
          docker compose logs redis
      
      - name : Stop and Remove Containers
        run: |
          docker compose down
        