name : push ci-cd pipeline
on : 
  push:
    branches: 
      - main
    paths:
      - 'app/**'
      - '.github/workflows/push-pr.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/push-pr.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses: actions/Checkout@v2
      - name : Python Set up
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run : |
          pip install -r app/requirements.txt
      - name: Run Flask App in Background
        run: |
          nohup python app/app.py &
          sleep 20

      - name: Test Flask App with curl
        run: |
          echo "Testing Flask App..."
          curl -i http://127.0.0.1:5000 || echo "Failed to reach Flask app"

      - name: Done
        run: echo "CI finished ✅"
