name : Flask-WebApp CI/CD
on : 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs :
  build-flask-app:
    runs-on: ubuntu-latest

    services:
      mysql:
        image : mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: DB
          MYSQL_USER: USER
          MYSQL_PASSWORD: PASSWORD
        options: >-
          --health-cmd "mysqladmin ping -h localhost -u root --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    
    steps:
      - name : Checkout Flask-WebApp
        uses: actions/checkout@v2
      
      - name : Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name : install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      
      - name : Wait for services
        run : sleep 10
      
      - name : Run Flask App and Test it
        env :
          DB_HOST: mysql
          DB_USER: USER
          DB_PASSWORD: PASSWORD
          DB_NAME: DB
  
          REDIS_HOST: redis
          SECRET_KEY: mysecretkey
        run: |
          python3 app/app.py
          sleep 5
          python3 app/test_app.py